name: Execute Commands on VM

on:
  push
 
jobs:
  execute_commands:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 172.190.178.221
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Commands on VM
        run: |
          pwd 
          ls
